# Generated by Django 3.1.3 on 2020-11-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videourl',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
