# Generated by Django 3.1.3 on 2020-11-17 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_videourl_downloaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='videourl',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
